// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

using System;
using System.Runtime.InteropServices;

public static class EquilibriumImports
{
    [DllImport("crepuscularity_abi")]
    public static extern IntPtr crepus_last_error();
    [DllImport("crepuscularity_abi")]
    public static extern void crepus_string_free(IntPtr ptr);
}
