// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

#include "crepuscularity_abi.h"

extern "C" {
char * eq_crepuscularity_abi_crepus_last_error() {
    return crepus_last_error();
}
void eq_crepuscularity_abi_crepus_string_free(char * ptr) {
    crepus_string_free(ptr);
}
}
