[package]
name = "weather"
version = "0.3.4"
edition = "2021"
license.workspace = true
publish = false

[[bin]]
name = "weather"
path = "src/main.rs"

[dependencies]
gpui = { workspace = true }
gpui_platform = { workspace = true }
crepuscularity-gpui = { path = "../../crates/crepuscularity-gpui", version = "0.5.10" }
