// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

#flag -I /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include
#include "crepuscularity_abi.h"

fn C.crepus_last_error() &char
fn C.crepus_string_free(ptr &char)
