//! Generate consumer-language imports from `crepuscularity_abi.h` via [equilibrium-ffi].
//!
//! One-shot entry: [`generate_all`] reads `plugins/crepuscularity-plugins.toml` and writes
//! `abi_generated.<ext>` next to each package path.

use std::path::{Path, PathBuf};

use equilibrium_ffi::{generate_imports, ImportOptions, Language};
use serde::Deserialize;

mod crepus_abi;

#[derive(Debug, Deserialize)]
struct PluginsManifest {
    contract: Contract,
    package: Vec<Package>,
}

#[derive(Debug, Deserialize)]
struct Contract {
    abi_header: String,
}

#[derive(Debug, Deserialize)]
struct Package {
    language: String,
    path: String,
}

#[derive(Clone, Debug)]
pub struct BindgenOptions {
    pub repo_root: PathBuf,
    pub manifest_path: PathBuf,
    pub abi_header: Option<PathBuf>,
    pub out_dir: Option<PathBuf>,
}

#[derive(Clone, Debug)]
pub struct GeneratedFile {
    pub language: String,
    pub path: PathBuf,
}

pub fn default_manifest_path(repo_root: &Path) -> PathBuf {
    repo_root.join("plugins/crepuscularity-plugins.toml")
}

pub fn resolve_abi_header(repo_root: &Path, contract_rel: &str) -> PathBuf {
    repo_root.join(contract_rel)
}

/// Map `crepuscularity-plugins.toml` language id → equilibrium consumer (if any).
fn equilibrium_language(id: &str) -> Option<Language> {
    // These names are repository adapters, even when equilibrium adds a new
    // consumer with the same name (notably TypeScript/ScriptC).
    match id {
        "go" | "python" | "java" | "kotlin" | "swift" | "php" | "ruby" | "typescript" => None,
        _ => Language::from_cli_name(id),
    }
}

fn output_filename(language: &str) -> &'static str {
    match language {
        "rust" => "abi_generated.rs",
        "zig" => "abi_generated.zig",
        "c" => "abi_generated.c",
        "cpp" => "abi_generated.cpp",
        "csharp" => "AbiGenerated.cs",
        "d" => "abi_generated.d",
        "nim" => "abi_generated.nim",
        "odin" => "abi_generated.odin",
        "hare" => "abi_generated.ha",
        "v" => "abi_generated.v",
        "go" => "abi_generated.go",
        "python" => "abi_generated.py",
        "java" => "AbiGenerated.java",
        "kotlin" => "AbiGenerated.kt",
        "swift" => "AbiGenerated.swift",
        "php" => "abi_generated.php",
        "ruby" => "abi_generated.rb",
        "typescript" => "abi_generated.ts",
        _ => "abi_generated.txt",
    }
}

fn load_manifest(path: &Path) -> Result<PluginsManifest, String> {
    let raw = std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    toml::from_str(&raw).map_err(|e| format!("parse {}: {e}", path.display()))
}

pub fn generate_all(opts: &BindgenOptions) -> Result<Vec<GeneratedFile>, String> {
    let manifest = load_manifest(&opts.manifest_path)?;
    let header = opts
        .abi_header
        .clone()
        .unwrap_or_else(|| resolve_abi_header(&opts.repo_root, &manifest.contract.abi_header));

    if !header.is_file() {
        return Err(format!(
            "ABI header not found: {} (build: cargo build -p crepuscularity-abi)",
            header.display()
        ));
    }

    let checked = crepus_abi::check_header(&header)?;
    let import_opts = ImportOptions::default();
    let mut prepared = Vec::new();

    for pkg in &manifest.package {
        let base = opts
            .out_dir
            .clone()
            .unwrap_or_else(|| opts.repo_root.clone());
        let pkg_dir = base.join(&pkg.path);
        let code = if let Some(lang) = equilibrium_language(&pkg.language) {
            if checked.canonical {
                crepus_abi::generate(&header, lang)?
            } else {
                if let Some(error) = &checked.fallback_error {
                    return Err(error.clone());
                }
                let generated = generate_imports(&header, lang, &import_opts)?;
                if !generated.warnings.is_empty() {
                    return Err(format!(
                        "{} bindings for {} are incomplete: {}",
                        pkg.language,
                        header.display(),
                        generated.warnings.join("; ")
                    ));
                }
                if !generated.companions.is_empty() {
                    return Err(format!(
                        "{} bindings require companion files; this backend is not supported",
                        pkg.language
                    ));
                }
                if pkg.language == "csharp" {
                    patch_csharp(&generated.code)
                } else {
                    generated.code
                }
            }
        } else {
            generate_extra(&pkg.language, &header)?
        };

        let file_name = output_filename(&pkg.language);
        let out_path = pkg_dir.join(file_name);
        let full = if pkg.language == "python" {
            format!(
                "# Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)\n# Source: {}\n\n{}",
                header.display(),
                code
            )
        } else {
            format!(
                "// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)\n// Source: {}\n\n{}",
                header.display(),
                code
            )
        };

        prepared.push((
            GeneratedFile {
                language: pkg.language.clone(),
                path: out_path,
            },
            full,
        ));
    }

    // A warning or unsupported later package must not replace earlier outputs.
    let mut written = Vec::new();
    for (file, content) in prepared {
        let parent = file.path.parent().expect("generated file has a parent");
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
        std::fs::write(&file.path, content)
            .map_err(|e| format!("write {}: {e}", file.path.display()))?;
        written.push(file);
    }
    Ok(written)
}

fn patch_csharp(code: &str) -> String {
    code.replace("IntPtr *", "IntPtr")
}

fn patch_go_cgo(code: &str) -> String {
    let preamble = r#"#cgo CFLAGS: -I${SRCDIR}/../../crates/crepuscularity-abi/include
#cgo LDFLAGS: -L${SRCDIR}/../../target/debug -lcrepuscularity_abi
#include "crepuscularity_abi.h""#;
    if let Some(start) = code.find("/*") {
        if let Some(end) = code[start..].find("*/") {
            let before = &code[..start];
            let after = &code[start + end + 2..];
            return format!("{before}/*\n{preamble}\n*/{after}");
        }
    }
    format!(
        r#"package crepuscularity

/*
{preamble}
*/
import "C"
{code}"#
    )
}

fn generate_extra(language: &str, header: &Path) -> Result<String, String> {
    let include_name = header
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("crepuscularity_abi.h");
    match language {
        "go" => Ok(patch_go_cgo(&format!(
            r#"// Package crepuscularity — low-level ABI (generated). Link libcrepuscularity_abi.
package crepuscularity

/*
#cgo LDFLAGS: -lcrepuscularity_abi
#include "{include_name}"
*/
import "C"
"#
        ))),
        "python" => Ok(generate_python_ctypes()),
        "java" => Ok(generate_java_jni(include_name)),
        "kotlin" => Ok(generate_kotlin_ffi(include_name)),
        "swift" => Ok(generate_swift_module(include_name)),
        "php" => Ok(generate_php_ffi()),
        "ruby" => Ok(generate_ruby_ffi()),
        "typescript" => Ok(generate_ts_koffi_stub()),
        _ => Err(format!(
            "language {language} has no bindgen backend; add to equilibrium or extra generator"
        )),
    }
}

fn generate_python_ctypes() -> String {
    r#"from __future__ import annotations

import ctypes
import json
import os
import sys
from pathlib import Path
from typing import Any, Callable


def _default_lib() -> str:
    root = Path(__file__).resolve().parents[2]
    suffix = {"darwin": "dylib", "linux": "so", "win32": "dll"}.get(sys.platform, "so")
    name = "libcrepuscularity_abi." + suffix
    return str(root / "target" / "debug" / name)


class CrepusAbiSession:
    def __init__(self, lib_path: str | None = None) -> None:
        self._lib = ctypes.CDLL(lib_path or os.environ.get("CREPUS_ABI_LIB") or _default_lib())
        self._callback_type = ctypes.CFUNCTYPE(None, ctypes.c_char_p, ctypes.c_void_p)
        self._callback_ref: Any = None
        self._configure()
        self._ptr = self._lib.crepus_session_new()
        if not self._ptr:
            raise RuntimeError("crepus_session_new failed")

    def _configure(self) -> None:
        self._lib.crepus_session_new.restype = ctypes.c_void_p
        self._lib.crepus_session_free.argtypes = [ctypes.c_void_p]
        self._lib.crepus_session_set_template_string.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_char_p]
        self._lib.crepus_session_set_template_string.restype = ctypes.c_int32
        self._lib.crepus_session_set_context_json.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
        self._lib.crepus_session_set_context_json.restype = ctypes.c_int32
        self._lib.crepus_session_apply_context_patch_json.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
        self._lib.crepus_session_apply_context_patch_json.restype = ctypes.c_int32
        self._lib.crepus_session_set_event_callback.argtypes = [ctypes.c_void_p, self._callback_type, ctypes.c_void_p]
        self._lib.crepus_session_set_event_callback.restype = ctypes.c_int32
        self._lib.crepus_session_render_ir_json.argtypes = [ctypes.c_void_p]
        self._lib.crepus_session_render_ir_json.restype = ctypes.c_void_p
        self._lib.crepus_session_dispatch_event_json.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
        self._lib.crepus_session_dispatch_event_json.restype = ctypes.c_void_p
        self._lib.crepus_session_take_last_error.argtypes = [ctypes.c_void_p]
        self._lib.crepus_session_take_last_error.restype = ctypes.c_void_p
        self._lib.crepus_last_error.restype = ctypes.c_void_p
        self._lib.crepus_string_free.argtypes = [ctypes.c_void_p]
"#
    .to_string()
}

fn generate_java_jni(include_name: &str) -> String {
    format!(
        r#"// JNI stubs — load libcrepuscularity_abi and declare native methods (fill via javac -h).
// Include path: copy or symlink {include_name} into jni include dir.

public final class AbiGenerated {{
    static {{
        System.loadLibrary("crepuscularity_abi");
    }}

    public static native long crepus_session_new();
    public static native void crepus_session_free(long session);
    public static native int crepus_session_set_template_string(long session, String templateUtf8, String baseDirUtf8);
    public static native int crepus_session_set_context_json(long session, String contextJsonUtf8);
    public static native String crepus_session_render_ir_json(long session);
    public static native String crepus_session_dispatch_event_json(long session, String eventJsonUtf8);
}}
"#
    )
}

fn generate_kotlin_ffi(_include_name: &str) -> String {
    r#"// Kotlin/JVM — same JNI surface as AbiGenerated.java
object AbiGenerated {
    init {
        System.loadLibrary("crepuscularity_abi")
    }
    external fun crepus_session_new(): Long
    external fun crepus_session_free(session: Long)
    external fun crepus_session_set_template_string(session: Long, templateUtf8: String, baseDirUtf8: String?): Int
    external fun crepus_session_set_context_json(session: Long, contextJsonUtf8: String): Int
    external fun crepus_session_render_ir_json(session: Long): String
    external fun crepus_session_dispatch_event_json(session: Long, eventJsonUtf8: String): String
}
"#
    .to_string()
}

fn generate_swift_module(_include_name: &str) -> String {
    r#"// Swift — link libcrepuscularity_abi; expand with SwiftPM module map.
import Foundation

@_silgen_name("crepus_session_new")
func crepus_session_new() -> UnsafeMutableRawPointer?

@_silgen_name("crepus_session_free")
func crepus_session_free(_ session: UnsafeMutableRawPointer?)

@_silgen_name("crepus_session_render_ir_json")
func crepus_session_render_ir_json(_ session: UnsafeMutableRawPointer?) -> UnsafeMutablePointer<CChar>?
"#
    .to_string()
}

fn generate_php_ffi() -> String {
    r#"<?php
// FFI — PHP 7.4+; set CREPUS_ABI_LIB to libcrepuscularity_abi path
final class AbiGenerated {
    private static ?\FFI $ffi = null;

    public static function ffi(): \FFI {
        if (self::$ffi === null) {
            $lib = getenv('CREPUS_ABI_LIB') ?: 'libcrepuscularity_abi.dylib';
            self::$ffi = \FFI::cdef(
                'typedef struct CrepusSession CrepusSession;
                 CrepusSession *crepus_session_new(void);
                 void crepus_session_free(CrepusSession *session);
                 char *crepus_session_render_ir_json(CrepusSession *session);
                 void crepus_string_free(char *ptr);',
                $lib
            );
        }
        return self::$ffi;
    }
}
"#
    .to_string()
}

fn generate_ruby_ffi() -> String {
    r#"# frozen_string_literal: true
require "fiddle"
require "fiddle/import"

module AbiGenerated
  extend Fiddle::Importer
  dlload ENV.fetch("CREPUS_ABI_LIB", "libcrepuscularity_abi.dylib")
  extern "void* crepus_session_new()"
  extern "void crepus_session_free(void*)"
  extern "char* crepus_session_render_ir_json(void*)"
  extern "void crepus_string_free(char*)"
end
"#
    .to_string()
}

fn generate_ts_koffi_stub() -> String {
    r#"// Bun/Node: use koffi or bun:ffi against libcrepuscularity_abi
// import koffi from "koffi";
// const lib = koffi.load(process.env.CREPUS_ABI_LIB ?? "libcrepuscularity_abi.dylib");
// export const crepus_session_new = lib.func("void* crepus_session_new()");
export {};
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_parses() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let path = default_manifest_path(&root);
        let m = load_manifest(&path).expect("manifest");
        assert!(m.package.iter().any(|p| p.language == "zig"));
    }
}
