// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

use std::os::raw::*;

extern "C" {
    pub fn crepus_last_error() -> *mut c_char;
    pub fn crepus_string_free(ptr: *mut c_char);
}
