//! Moonshine JSX emitter, promoted from the CLI so external Rust projects can call it.
//!
//! HTML is the real production path (`build_site_wasm`). `--emit moonshine` writes
//! a real `@tschk/crepus-moonshine` app entry under `dist/`.

use crate::ir::{ViewIr, ViewNode, ViewStyle};
use crate::js_expr::scope_expr;

/// Shared preamble emitted by both entry points: the `Fragment` import used by
/// `ForEach` and the `toArray` guard so a missing/non-array scope value renders
/// nothing instead of throwing.
const RUNTIME_PREAMBLE: &str = r#"import { Fragment } from "react";

const toArray = (v: unknown): any[] => (Array.isArray(v) ? v : []);
"#;

/// The emitted props contract shared by both the app and component emitters:
/// `<Name>Scope`, `<Name>Handlers`, `<Name>Props`, and the destructured
/// function signature that opens the component body.
fn props_contract(name: &str) -> String {
    format!(
        // `any`, not `unknown`: template expressions compare and dereference
        // scope values (`count > 0`, `user.name`), and `unknown` makes every one
        // of those a TS18046 error in the consumer's build. The template
        // language is untyped, so the boundary is where the typing stops.
        r#"export type {name}Scope = Record<string, any>;
export type {name}Handlers = Record<string, (...args: any[]) => void>;
export type {name}Props = {{ scope?: {name}Scope; handlers?: {name}Handlers }};
"#
    )
}

/// Emit a Moonshine app entry as real JSX, preserving the original class tokens
/// as `className` so UnoCSS/Tailwind styles the output.
///
/// Output is valid TSX: `App` + optional `mount` helper using `@tschk/moonshine/react`.
pub fn emit_moonshine_app(ir: &ViewIr) -> String {
    let locals: Vec<String> = Vec::new();
    let children: String = ir
        .root
        .iter()
        .map(|n| emit_jsx_node(n, 3, &locals))
        .collect::<Vec<_>>()
        .join("\n");
    let contract = props_contract("App");
    let mut body = format!(
        r#"// Generated by crepus web build --emit moonshine
import {{ createApp }} from "@tschk/moonshine/react";
{RUNTIME_PREAMBLE}
{contract}
export function App({{ scope = {{}}, handlers = {{}} }}: AppProps) {{
  return (
    <div data-crepus-root="true">
{children}
    </div>
  );
}}
"#
    );
    body.push_str(
        r##"
// Optional mount helper for Vite entry
export function mount(selector = "#app") {
  createApp({ root: App }).mount(selector);
}

export default App;
"##,
    );
    body
}

/// Emit the same JSX tree as [`emit_moonshine_app`] but as a named, importable
/// component instead of an app entry: no `createApp` import, no `mount` helper.
pub fn emit_moonshine_component(ir: &ViewIr, component_name: &str) -> String {
    let locals: Vec<String> = Vec::new();
    let children: String = ir
        .root
        .iter()
        .map(|n| emit_jsx_node(n, 3, &locals))
        .collect::<Vec<_>>()
        .join("\n");
    let contract = props_contract(component_name);
    format!(
        r#"// Generated by crepus web build --emit moonshine
{RUNTIME_PREAMBLE}
{contract}
export function {component_name}({{ scope = {{}}, handlers = {{}} }}: {component_name}Props) {{
  return (
    <div data-crepus-root="true">
{children}
    </div>
  );
}}

export default {component_name};
"#
    )
}

/// JSON-escape a string for use inside a JSX expression container.
fn js_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// A string-valued JSX attribute, written the way a person writes it:
/// `name="value"`. The braced form is only used when the value cannot sit
/// inside a quoted literal, since `name={"value"}` is legal but not idiomatic.
fn attr(name: &str, value: &str) -> String {
    let needs_expr = value
        .chars()
        .any(|c| c == '"' || c == '\\' || (c as u32) < 0x20);
    if needs_expr {
        format!(" {name}={{{}}}", js_str(value))
    } else {
        format!(" {name}=\"{value}\"")
    }
}

/// A JSX text child, written literally rather than as `{"..."}`. Characters
/// JSX reads as markup or as an HTML entity force the braced form, because
/// literal text containing them would not round-trip.
fn jsx_text(content: &str) -> String {
    let needs_expr = content.is_empty()
        || content != content.trim()
        || content
            .chars()
            .any(|c| matches!(c, '{' | '}' | '<' | '>' | '&') || (c as u32) < 0x20);
    if needs_expr {
        format!("{{{}}}", js_str(content))
    } else {
        content.to_string()
    }
}

/// `className="..."` from the class tokens the parser preserved on the node.
fn class_attr(style: Option<&ViewStyle>) -> String {
    let classes = match style {
        Some(s) if !s.classes.is_empty() => s.classes.join(" "),
        _ => return String::new(),
    };
    attr("className", &classes)
}

fn opt_attr(name: &str, value: Option<&String>) -> String {
    match value {
        Some(v) => attr(name, v),
        None => String::new(),
    }
}

fn on_click_attr(name: &str) -> String {
    format!(" onClick={{() => handlers.{name}?.()}}")
}

fn dom_event_attr(js_event: &str, name: &str) -> String {
    format!(" {js_event}={{(event) => handlers.{name}?.(event)}}")
}

fn opt_on_click(v: Option<&String>) -> String {
    v.map(|n| on_click_attr(n)).unwrap_or_default()
}

fn opt_dom_event(js_event: &str, v: Option<&String>) -> String {
    v.map(|n| dom_event_attr(js_event, n)).unwrap_or_default()
}

fn opt_on_long_press(v: Option<&String>) -> String {
    v.map(|n| attr("data-crepus-on-long-press", n))
        .unwrap_or_default()
}

fn emit_children(children: &[ViewNode], indent: usize, locals: &[String]) -> String {
    children
        .iter()
        .map(|c| emit_jsx_node(c, indent, locals))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Wrap `children` in `tag`, or self-close when there are none.
fn element(
    tag: &str,
    attrs: &str,
    children: &[ViewNode],
    indent: usize,
    locals: &[String],
) -> String {
    let pad = "  ".repeat(indent);
    if children.is_empty() {
        return format!("{pad}<{tag}{attrs} />");
    }
    let inner = emit_children(children, indent + 1, locals);
    format!("{pad}<{tag}{attrs}>\n{inner}\n{pad}</{tag}>")
}

/// `{COND ? (<>...then...</>) : (<>...else...</> | null)}`.
fn emit_if(
    condition: &str,
    then_children: &[ViewNode],
    else_children: Option<&Vec<ViewNode>>,
    indent: usize,
    locals: &[String],
) -> String {
    let pad = "  ".repeat(indent);
    let cond = scope_expr(condition, locals, "scope.");
    let then_jsx = format!(
        "{pad}  <>\n{}\n{pad}  </>",
        emit_children(then_children, indent + 2, locals)
    );
    let (else_open, else_body, else_close) = match else_children {
        None => ("", "null".to_string(), ""),
        Some(ec) => (
            "(\n",
            format!(
                "{pad}  <>\n{}\n{pad}  </>",
                emit_children(ec, indent + 2, locals)
            ),
            "\n{pad})",
        ),
    };
    let else_close = else_close.replace("{pad}", &pad);
    format!("{pad}{{{cond} ? (\n{then_jsx}\n{pad}) : {else_open}{else_body}{else_close}}}")
}

/// `{toArray(scope.BIND).map((ITEM, index) => (<Fragment key={index}>...</Fragment>))}`.
fn emit_for_each(
    bind: &str,
    item_name: &str,
    item_body: &[ViewNode],
    indent: usize,
    locals: &[String],
) -> String {
    let pad = "  ".repeat(indent);
    let bind_expr = scope_expr(bind, locals, "scope.");
    let mut inner_locals = locals.to_vec();
    inner_locals.push(item_name.to_string());
    let inner = emit_children(item_body, indent + 2, &inner_locals);
    format!(
        "{pad}{{toArray({bind_expr}).map(({item_name}, index) => (\n{pad}  <Fragment key={{index}}>\n{inner}\n{pad}  </Fragment>\n{pad}))}}"
    )
}

fn emit_jsx_node(node: &ViewNode, indent: usize, locals: &[String]) -> String {
    let pad = "  ".repeat(indent);
    match node {
        ViewNode::Text {
            content,
            bind,
            style,
        } => {
            let body = match bind {
                Some(b) => format!("{{{}}}", scope_expr(b, locals, "scope.")),
                None => jsx_text(content),
            };
            format!("{pad}<span{}>{}</span>", class_attr(style.as_ref()), body)
        }
        ViewNode::Link {
            href,
            target,
            rel,
            style,
            children,
        } => {
            let attrs = format!(
                "{}{}{}{}",
                attr("href", href),
                opt_attr("target", target.as_ref()),
                opt_attr("rel", rel.as_ref()),
                class_attr(style.as_ref())
            );
            element("a", &attrs, children, indent, locals)
        }
        ViewNode::Stack {
            on_long_press,
            style,
            children,
            ..
        } => {
            let attrs = format!("{}{}", class_attr(style.as_ref()), opt_on_long_press(on_long_press.as_ref()));
            element("div", &attrs, children, indent, locals)
        }
        ViewNode::Scroll { style, children, .. } => {
            element("div", &class_attr(style.as_ref()), children, indent, locals)
        }
        ViewNode::Dropzone {
            on_drop,
            style,
            children,
            ..
        } => {
            let attrs = format!("{}{}", class_attr(style.as_ref()), opt_dom_event("onDrop", on_drop.as_ref()));
            element("div", &attrs, children, indent, locals)
        }
        ViewNode::List {
            ordered,
            style,
            children,
        } => element(
            if *ordered { "ol" } else { "ul" },
            &class_attr(style.as_ref()),
            children,
            indent,
            locals,
        ),
        ViewNode::ListItem {
            on_long_press,
            style,
            children,
        } => {
            let attrs = format!("{}{}", class_attr(style.as_ref()), opt_on_long_press(on_long_press.as_ref()));
            element("li", &attrs, children, indent, locals)
        }
        ViewNode::Button {
            label,
            on_click,
            on_long_press,
            style,
        } => format!(
            "{pad}<button type=\"button\"{}{}{}>{}</button>",
            class_attr(style.as_ref()),
            opt_on_click(on_click.as_ref()),
            opt_on_long_press(on_long_press.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Badge { label, tone, style, .. } => format!(
            "{pad}<span{}{}>{}</span>",
            class_attr(style.as_ref()),
            opt_attr("data-tone", tone.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Divider { style, .. } => {
            format!("{pad}<hr{} />", class_attr(style.as_ref()))
        }
        ViewNode::Spacer { style, .. } => {
            format!("{pad}<div aria-hidden=\"true\"{} />", class_attr(style.as_ref()))
        }
        ViewNode::Image {
            src,
            alt,
            on_long_press,
            style,
            ..
        } => format!(
            "{pad}<img{}{}{}{} />",
            attr("src", src),
            attr("alt", alt.as_deref().unwrap_or("")),
            class_attr(style.as_ref()),
            opt_on_long_press(on_long_press.as_ref())
        ),
        ViewNode::WebView { src, style } => format!(
            "{pad}<iframe{}{} />",
            attr("src", src),
            class_attr(style.as_ref())
        ),
        ViewNode::Toggle {
            label,
            checked,
            on_change,
            on_long_press,
            style,
            ..
        } => format!(
            "{pad}<button type=\"button\" role=\"switch\" aria-checked={{{}}}{}{}{}>{}</button>",
            checked,
            class_attr(style.as_ref()),
            opt_dom_event("onChange", on_change.as_ref()),
            opt_on_long_press(on_long_press.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Checkbox {
            label,
            checked,
            on_change,
            style,
            ..
        } => format!(
            "{pad}<label{}>\n{pad}  <input type=\"checkbox\" defaultChecked={{{}}}{} />\n{pad}  {}\n{pad}</label>",
            class_attr(style.as_ref()),
            checked,
            opt_dom_event("onChange", on_change.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Slider {
            value,
            min,
            max,
            step,
            on_change,
            style,
            ..
        } => format!(
            "{pad}<input type=\"range\" defaultValue={{{value}}} min={{{min}}} max={{{max}}}{}{}{} />",
            step.map(|s| format!(" step={{{s}}}")).unwrap_or_default(),
            class_attr(style.as_ref()),
            opt_dom_event("onChange", on_change.as_ref())
        ),
        ViewNode::Progress {
            value, max, style, ..
        } => format!(
            "{pad}<progress value={{{value}}} max={{{max}}}{} />",
            class_attr(style.as_ref())
        ),
        ViewNode::Meter {
            value,
            min,
            max,
            style,
            ..
        } => format!(
            "{pad}<meter value={{{value}}} min={{{min}}} max={{{max}}}{} />",
            class_attr(style.as_ref())
        ),
        ViewNode::Input {
            placeholder,
            bind,
            secure,
            multiline,
            on_change,
            style,
        } => {
            let cls = class_attr(style.as_ref());
            let ph = attr("placeholder", placeholder);
            let name = attr("name", bind);
            let on_change_attr = opt_dom_event("onChange", on_change.as_ref());
            if *multiline {
                format!("{pad}<textarea{ph}{name}{cls}{on_change_attr} />")
            } else {
                let ty = if *secure { "password" } else { "text" };
                format!("{pad}<input type=\"{ty}\"{ph}{name}{cls}{on_change_attr} />")
            }
        }
        ViewNode::Picker {
            options,
            bind,
            on_change,
            style,
        } => {
            let opts: String = options
                .iter()
                .map(|o| {
                    format!(
                        "{pad}  <option{}>{}</option>",
                        attr("value", &o.value),
                        jsx_text(&o.label)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "{pad}<select{}{}{}>\n{opts}\n{pad}</select>",
                attr("name", bind),
                class_attr(style.as_ref()),
                opt_dom_event("onChange", on_change.as_ref())
            )
        }
        ViewNode::FilePicker {
            label,
            accept,
            multiple,
            on_pick,
            style,
        } => {
            let accept_attr = if accept.is_empty() {
                String::new()
            } else {
                attr("accept", &accept.join(","))
            };
            let multiple_attr = if *multiple { " multiple" } else { "" };
            format!(
                "{pad}<label{}>\n{pad}  <input type=\"file\"{accept_attr}{multiple_attr}{} />\n{pad}  {}\n{pad}</label>",
                class_attr(style.as_ref()),
                opt_dom_event("onChange", on_pick.as_ref()),
                jsx_text(label)
            )
        }
        ViewNode::SlotRotate {
            phrases,
            interval_ms,
            style,
        } => format!(
            "{pad}<span{} data-interval-ms={{{interval_ms}}}{}>{}</span>",
            attr("data-crepus-slot-rotate", &phrases.join("|")),
            class_attr(style.as_ref()),
            jsx_text(phrases.first().map(String::as_str).unwrap_or(""))
        ),
        ViewNode::Tabs {
            tabs,
            on_change,
            style,
            ..
        } => {
            let cls = class_attr(style.as_ref());
            let buttons: String = tabs
                .iter()
                .map(|t| {
                    let onclick = match on_change {
                        Some(name) => format!(" onClick={{() => handlers.{name}?.({})}}", js_str(&t.value)),
                        None => String::new(),
                    };
                    format!(
                        "{pad}    <button type=\"button\" role=\"tab\"{onclick}>{}</button>",
                        jsx_text(&t.label)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            let panels: String = tabs
                .iter()
                .map(|t| {
                    format!(
                        "{pad}  <div role=\"tabpanel\">\n{}\n{pad}  </div>",
                        emit_children(&t.children, indent + 2, locals)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "{pad}<div{cls}>\n{pad}  <div role=\"tablist\">\n{buttons}\n{pad}  </div>\n{panels}\n{pad}</div>"
            )
        }
        ViewNode::If {
            condition,
            then_children,
            else_children,
            ..
        } => emit_if(condition, then_children, else_children.as_ref(), indent, locals),
        ViewNode::ForEach {
            bind,
            item_name,
            item_body,
            ..
        } => emit_for_each(bind, item_name, item_body, indent, locals),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::render_template_to_ir;
    use crepuscularity_core::context::TemplateContext;

    fn sample_ir() -> ViewIr {
        let source = r#"stack col gap-2
 text "hi"
 button "Go"
"#;
        render_template_to_ir(source, &TemplateContext::new()).expect("ir")
    }

    #[test]
    fn moonshine_emit_writes_real_jsx_with_classnames() {
        let body = emit_moonshine_app(&sample_ir());
        assert!(body.contains("@tschk/moonshine/react"));
        assert!(body.contains("createApp"));
        assert!(body.contains("export function App"));
        assert!(body.contains("export function mount"));
        assert!(body.contains("data-crepus-root=\"true\""));
        // Real elements, not an IR blob handed to a runtime renderer.
        assert!(body.contains("<div className=\"col gap-2\">"));
        assert!(body.contains("<span>hi</span>"));
        assert!(body.contains("<button type=\"button\">Go</button>"));
        assert!(!body.contains("renderCrepusIr"));
        assert!(!body.contains("satisfies ViewIr"));
        assert!(!body.contains("TODO"));
    }

    #[test]
    fn moonshine_emit_preserves_anchor_href_and_classes() {
        let source =
            "a href=\"https://example.com\" no-underline text-zinc-100\n span \"crepuscularity\"\n";
        let ir = render_template_to_ir(source, &TemplateContext::new()).expect("ir");
        let body = emit_moonshine_app(&ir);
        assert!(body.contains("<a href=\"https://example.com\""));
        assert!(body.contains("className=\"no-underline text-zinc-100\""));
        assert!(body.contains(">crepuscularity</span>"));
    }

    #[test]
    fn text_containing_jsx_metacharacters_stays_in_an_expression() {
        // `{`, `}`, `<`, `>` and `&` are markup or entity syntax in a JSX text
        // child, so this content cannot be written literally.
        let source = "text \"a < b && c > d\"\n";
        let ir = render_template_to_ir(source, &TemplateContext::new()).expect("ir");
        let body = emit_moonshine_app(&ir);
        assert!(body.contains(r#"{"a < b && c > d"}"#), "{body}");
    }

    #[test]
    fn attribute_containing_a_quote_stays_in_an_expression() {
        let source = "a href=\"/a\\\"b\"\n span \"x\"\n";
        let ir = render_template_to_ir(source, &TemplateContext::new()).expect("ir");
        let body = emit_moonshine_app(&ir);
        assert!(!body.contains(r#"href="/a"b""#), "{body}");
    }

    #[test]
    fn component_emitter_uses_named_component() {
        let body = emit_moonshine_component(&sample_ir(), "Card");
        assert!(body.contains("export function Card"));
        assert!(body.contains("export default Card;"));
    }

    #[test]
    fn component_emitter_omits_create_app_and_mount() {
        let body = emit_moonshine_component(&sample_ir(), "Card");
        assert!(!body.contains("createApp"));
        assert!(!body.contains("export function mount"));
        assert!(!body.contains("@tschk/moonshine/react"));
    }

    #[test]
    fn component_emitter_renders_same_markup_as_app_emitter() {
        let ir = sample_ir();
        let app_body = emit_moonshine_app(&ir);
        let component_body = emit_moonshine_component(&ir, "Card");
        assert!(app_body.contains("<div className=\"col gap-2\">"));
        assert!(component_body.contains("<div className=\"col gap-2\">"));
        assert!(app_body.contains("<span>hi</span>"));
        assert!(component_body.contains("<span>hi</span>"));
        assert!(app_body.contains("<button type=\"button\">Go</button>"));
        assert!(component_body.contains("<button type=\"button\">Go</button>"));
    }

    // ── props contract ─────────────────────────────────────────────────────

    #[test]
    fn emits_scope_and_handlers_props_contract() {
        let body = emit_moonshine_app(&sample_ir());
        assert!(body.contains("export type AppScope = Record<string, any>;"));
        assert!(
            body.contains("export type AppHandlers = Record<string, (...args: any[]) => void>;")
        );
        assert!(
            body.contains("export type AppProps = { scope?: AppScope; handlers?: AppHandlers };")
        );
        assert!(body.contains("export function App({ scope = {}, handlers = {} }: AppProps)"));
    }

    #[test]
    fn component_emitter_uses_named_props_contract() {
        let body = emit_moonshine_component(&sample_ir(), "Card");
        assert!(body
            .contains("export type CardProps = { scope?: CardScope; handlers?: CardHandlers };"));
        assert!(body.contains("export function Card({ scope = {}, handlers = {} }: CardProps)"));
    }

    // ── scope_expr ──────────────────────────────────────────────────────────

    #[test]
    fn scope_expr_leaves_string_literals_untouched() {
        assert_eq!(
            scope_expr(r#"x == "yes""#, &[], "scope."),
            r#"scope.x == "yes""#
        );
        assert_eq!(scope_expr("x == 'yes'", &[], "scope."), "scope.x == 'yes'");
    }

    #[test]
    fn scope_expr_prefixes_dotted_path_once() {
        assert_eq!(scope_expr("user.name", &[], "scope."), "scope.user.name");
        assert_eq!(scope_expr("a.b.c", &[], "scope."), "scope.a.b.c");
    }

    #[test]
    fn scope_expr_does_not_prefix_locals() {
        assert_eq!(
            scope_expr("item.active", &["item".to_string()], "scope."),
            "item.active"
        );
    }

    #[test]
    fn scope_expr_does_not_prefix_keywords() {
        assert_eq!(scope_expr("true", &[], "scope."), "true");
        assert_eq!(scope_expr("x == null", &[], "scope."), "scope.x == null");
        assert_eq!(
            scope_expr("x || undefined", &[], "scope."),
            "scope.x || undefined"
        );
    }

    #[test]
    fn scope_expr_empty_becomes_undefined() {
        assert_eq!(scope_expr("", &[], "scope."), "undefined");
        assert_eq!(scope_expr("   ", &[], "scope."), "undefined");
    }

    #[test]
    fn scope_expr_leaves_numbers_and_operators_alone() {
        assert_eq!(scope_expr("count > 0", &[], "scope."), "scope.count > 0");
        assert_eq!(scope_expr("a && b", &[], "scope."), "scope.a && scope.b");
    }

    // ── events ──────────────────────────────────────────────────────────────

    #[test]
    fn button_on_click_wired_to_handlers() {
        let node = ViewNode::Button {
            label: "Go".to_string(),
            on_click: Some("go".to_string()),
            on_long_press: None,
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("onClick={() => handlers.go?.()}"), "{out}");
    }

    // ── bind ────────────────────────────────────────────────────────────────

    #[test]
    fn text_with_bind_renders_expression_not_literal() {
        let node = ViewNode::Text {
            content: "placeholder".to_string(),
            bind: Some("user.name".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert_eq!(out, "<span>{scope.user.name}</span>");
    }

    // ── if / else ───────────────────────────────────────────────────────────

    #[test]
    fn if_without_else_emits_null_branch() {
        let node = ViewNode::If {
            condition: "count > 0".to_string(),
            then_children: vec![ViewNode::Text {
                content: "yes".to_string(),
                bind: None,
                style: None,
            }],
            else_children: None,
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.starts_with("{scope.count > 0 ? ("), "{out}");
        assert!(out.contains("<span>yes</span>"), "{out}");
        assert!(out.trim_end().ends_with(") : null}"), "{out}");
    }

    #[test]
    fn if_with_else_renders_both_branches() {
        let node = ViewNode::If {
            condition: "count > 0".to_string(),
            then_children: vec![ViewNode::Text {
                content: "yes".to_string(),
                bind: None,
                style: None,
            }],
            else_children: Some(vec![ViewNode::Text {
                content: "no".to_string(),
                bind: None,
                style: None,
            }]),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("<span>yes</span>"), "{out}");
        assert!(out.contains("<span>no</span>"), "{out}");
        assert!(!out.contains(": null"), "{out}");
    }

    // ── forEach ─────────────────────────────────────────────────────────────

    #[test]
    fn for_each_maps_over_scope_array() {
        let node = ViewNode::ForEach {
            bind: "items".to_string(),
            item_name: "item".to_string(),
            item_body: vec![ViewNode::Text {
                content: "".to_string(),
                bind: Some("item.name".to_string()),
                style: None,
            }],
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.starts_with("{toArray(scope.items).map((item, index) => ("),
            "{out}"
        );
        assert!(out.contains("<Fragment key={index}>"), "{out}");
        assert!(out.contains("{item.name}"), "{out}");
        assert!(!out.contains("scope.item.name"), "{out}");
    }

    #[test]
    fn nested_for_each_resolves_both_item_names_as_locals() {
        let inner = ViewNode::ForEach {
            bind: "outer.children".to_string(),
            item_name: "inner".to_string(),
            item_body: vec![ViewNode::Text {
                content: "".to_string(),
                bind: Some("inner.label".to_string()),
                style: None,
            }],
            style: None,
        };
        let node = ViewNode::ForEach {
            bind: "items".to_string(),
            item_name: "outer".to_string(),
            item_body: vec![inner],
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        // Outer binds from `scope`; inner's bind resolves against the outer
        // loop variable (`outer`), not `scope`, since `outer` is a real local
        // once we're inside the outer ForEach's body.
        assert!(
            out.contains("toArray(scope.items).map((outer, index)"),
            "{out}"
        );
        assert!(
            out.contains("toArray(outer.children).map((inner, index)"),
            "{out}"
        );
        assert!(out.contains("{inner.label}"), "{out}");
        assert!(!out.contains("scope.inner.label"), "{out}");
        assert!(!out.contains("scope.outer.children"), "{out}");
    }

    // ── one test per ViewNode variant ──────────────────────────────────────

    #[test]
    fn emits_text() {
        let node = ViewNode::Text {
            content: "hi".to_string(),
            bind: None,
            style: None,
        };
        assert_eq!(emit_jsx_node(&node, 0, &[]), "<span>hi</span>");
    }

    #[test]
    fn emits_stack() {
        let node = ViewNode::Stack {
            axis: crate::ir::StackAxis::Column,
            spacing: None,
            align_items: None,
            justify_content: None,
            on_long_press: Some("press".to_string()),
            style: None,
            children: vec![],
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.contains(r#"data-crepus-on-long-press="press""#),
            "{out}"
        );
    }

    #[test]
    fn emits_button() {
        let node = ViewNode::Button {
            label: "Go".to_string(),
            on_click: None,
            on_long_press: None,
            style: None,
        };
        assert_eq!(
            emit_jsx_node(&node, 0, &[]),
            "<button type=\"button\">Go</button>"
        );
    }

    #[test]
    fn emits_toggle() {
        let node = ViewNode::Toggle {
            label: "On".to_string(),
            bind: None,
            checked: true,
            on_change: Some("toggle".to_string()),
            on_long_press: None,
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.contains("onChange={(event) => handlers.toggle?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_checkbox() {
        let node = ViewNode::Checkbox {
            label: "Agree".to_string(),
            bind: None,
            checked: false,
            on_change: Some("agree".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.contains("onChange={(event) => handlers.agree?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_slider() {
        let node = ViewNode::Slider {
            label: None,
            bind: None,
            value: 5.0,
            min: 0.0,
            max: 10.0,
            step: Some(1.0),
            on_change: Some("vol".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("type=\"range\""), "{out}");
        assert!(
            out.contains("onChange={(event) => handlers.vol?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_progress() {
        let node = ViewNode::Progress {
            label: None,
            value: 3.0,
            max: 10.0,
            style: None,
        };
        assert_eq!(
            emit_jsx_node(&node, 0, &[]),
            "<progress value={3} max={10} />"
        );
    }

    #[test]
    fn emits_meter() {
        let node = ViewNode::Meter {
            label: None,
            value: 3.0,
            min: 0.0,
            max: 10.0,
            style: None,
        };
        assert_eq!(
            emit_jsx_node(&node, 0, &[]),
            "<meter value={3} min={0} max={10} />"
        );
    }

    #[test]
    fn emits_badge() {
        let node = ViewNode::Badge {
            label: "New".to_string(),
            tone: Some("info".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("data-tone=\"info\""), "{out}");
    }

    #[test]
    fn emits_divider() {
        let node = ViewNode::Divider {
            axis: crate::ir::StackAxis::Row,
            style: None,
        };
        assert_eq!(emit_jsx_node(&node, 0, &[]), "<hr />");
    }

    #[test]
    fn emits_spacer() {
        let node = ViewNode::Spacer {
            size: None,
            style: None,
        };
        assert_eq!(emit_jsx_node(&node, 0, &[]), "<div aria-hidden=\"true\" />");
    }

    #[test]
    fn emits_dropzone() {
        let node = ViewNode::Dropzone {
            label: "Drop here".to_string(),
            accept: None,
            on_drop: Some("drop".to_string()),
            style: None,
            children: vec![],
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.contains("onDrop={(event) => handlers.drop?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_file_picker() {
        let node = ViewNode::FilePicker {
            label: "Upload".to_string(),
            accept: vec!["image/*".to_string()],
            multiple: true,
            on_pick: Some("upload".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("type=\"file\""), "{out}");
        assert!(out.contains("accept=\"image/*\""), "{out}");
        assert!(out.contains("multiple"), "{out}");
        assert!(
            out.contains("onChange={(event) => handlers.upload?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_image() {
        let node = ViewNode::Image {
            src: "cat.png".to_string(),
            alt: Some("A cat".to_string()),
            placeholder: None,
            on_long_press: Some("press".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("src=\"cat.png\""), "{out}");
        assert!(
            out.contains(r#"data-crepus-on-long-press="press""#),
            "{out}"
        );
    }

    #[test]
    fn emits_link() {
        let node = ViewNode::Link {
            href: "/about".to_string(),
            target: None,
            rel: None,
            style: None,
            children: vec![],
        };
        assert_eq!(emit_jsx_node(&node, 0, &[]), "<a href=\"/about\" />");
    }

    #[test]
    fn emits_web_view() {
        let node = ViewNode::WebView {
            src: "https://example.com".to_string(),
            style: None,
        };
        assert_eq!(
            emit_jsx_node(&node, 0, &[]),
            "<iframe src=\"https://example.com\" />"
        );
    }

    #[test]
    fn emits_scroll() {
        let node = ViewNode::Scroll {
            axis: crate::ir::StackAxis::Column,
            style: None,
            children: vec![],
        };
        assert_eq!(emit_jsx_node(&node, 0, &[]), "<div />");
    }

    #[test]
    fn emits_list() {
        let node = ViewNode::List {
            ordered: true,
            style: None,
            children: vec![],
        };
        assert_eq!(emit_jsx_node(&node, 0, &[]), "<ol />");
    }

    #[test]
    fn emits_list_item() {
        let node = ViewNode::ListItem {
            on_long_press: Some("press".to_string()),
            style: None,
            children: vec![],
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.contains(r#"data-crepus-on-long-press="press""#),
            "{out}"
        );
    }

    #[test]
    fn emits_slot_rotate() {
        let node = ViewNode::SlotRotate {
            phrases: vec!["hi".to_string(), "bye".to_string()],
            interval_ms: 500,
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("data-crepus-slot-rotate=\"hi|bye\""), "{out}");
        assert!(out.contains(">hi</span>"), "{out}");
    }

    #[test]
    fn emits_input() {
        let node = ViewNode::Input {
            placeholder: "Name".to_string(),
            bind: "name".to_string(),
            multiline: false,
            secure: false,
            on_change: Some("nameChanged".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("placeholder=\"Name\""), "{out}");
        assert!(
            out.contains("onChange={(event) => handlers.nameChanged?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_picker() {
        let node = ViewNode::Picker {
            bind: "color".to_string(),
            options: vec![],
            on_change: Some("colorChanged".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.contains("onChange={(event) => handlers.colorChanged?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_tabs() {
        let node = ViewNode::Tabs {
            bind: "tab".to_string(),
            tabs: vec![crate::ir::TabItem {
                value: "one".to_string(),
                label: "One".to_string(),
                icon: None,
                children: vec![],
            }],
            on_change: Some("tabChanged".to_string()),
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(
            out.contains("onClick={() => handlers.tabChanged?.(\"one\")}"),
            "{out}"
        );
    }

    #[test]
    fn emits_if() {
        let node = ViewNode::If {
            condition: "flag".to_string(),
            then_children: vec![],
            else_children: None,
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.starts_with("{scope.flag ? ("), "{out}");
    }

    #[test]
    fn emits_for_each() {
        let node = ViewNode::ForEach {
            bind: "items".to_string(),
            item_name: "item".to_string(),
            item_body: vec![],
            style: None,
        };
        let out = emit_jsx_node(&node, 0, &[]);
        assert!(out.contains("toArray(scope.items).map"), "{out}");
    }
}
