//! SolidJS TSX emitter, mirroring `moonshine.rs`'s React emitter but targeting
//! Solid's reactive-accessor idiom (`scope()` / `handlers()`) and control-flow
//! components (`<Show>` / `<For>`) instead of ternaries and `.map`.

use crate::ir::{ViewIr, ViewNode, ViewStyle};
use crate::utils::js_str;

/// Shared preamble: the `For`/`Show` imports and the `toArray` guard so a
/// missing/non-array scope value renders nothing instead of throwing.
const RUNTIME_PREAMBLE: &str = r#"import { For, Show } from "solid-js";

const toArray = (v: unknown): any[] => (Array.isArray(v) ? v : []);
"#;

/// The emitted props contract: `<Name>Props` plus the `scope`/`handlers`
/// accessor helpers that open the component body.
fn props_contract(name: &str) -> String {
    format!(
        r#"export type {name}Props = {{ scope?: Record<string, any>; handlers?: Record<string, any> }};
"#
    )
}

/// Emit a Solid component as real TSX, preserving the original class tokens
/// as `class` so UnoCSS/Tailwind styles the output.
pub fn emit_solid_component(ir: &ViewIr, component_name: &str) -> String {
    let locals: Vec<String> = Vec::new();
    let children: String = ir
        .root
        .iter()
        .map(|n| emit_node(n, 3, &locals))
        .collect::<Vec<_>>()
        .join("\n");
    let contract = props_contract(component_name);
    format!(
        r#"// Generated by crepus web build --emit solid
{RUNTIME_PREAMBLE}
{contract}
export function {component_name}(props: {component_name}Props) {{
  const scope = () => props.scope ?? {{}};
  const handlers = () => props.handlers ?? {{}};
  return (
    <div data-crepus-root="true">
{children}
    </div>
  );
}}

export default {component_name};
"#
    )
}

/// A string-valued JSX attribute, written the way a person writes it:
/// `name="value"`. The braced form is only used when the value cannot sit
/// inside a quoted literal, since `name={"value"}` is legal but not idiomatic.
fn attr(name: &str, value: &str) -> String {
    let needs_expr = value
        .chars()
        .any(|c| c == '"' || c == '\\' || (c as u32) < 0x20);
    if needs_expr {
        format!(" {name}={{{}}}", js_str(value))
    } else {
        format!(" {name}=\"{value}\"")
    }
}

/// A JSX text child, written literally rather than as `{"..."}`. Characters
/// JSX reads as markup or as an HTML entity force the braced form, because
/// literal text containing them would not round-trip.
fn jsx_text(content: &str) -> String {
    let needs_expr = content.is_empty()
        || content != content.trim()
        || content
            .chars()
            .any(|c| matches!(c, '{' | '}' | '<' | '>' | '&') || (c as u32) < 0x20);
    if needs_expr {
        format!("{{{}}}", js_str(content))
    } else {
        content.to_string()
    }
}

/// `class="..."` from the class tokens the parser preserved on the node.
fn class_attr(style: Option<&ViewStyle>) -> String {
    let classes = match style {
        Some(s) if !s.classes.is_empty() => s.classes.join(" "),
        _ => return String::new(),
    };
    attr("class", &classes)
}

fn opt_attr(name: &str, value: Option<&String>) -> String {
    match value {
        Some(v) => attr(name, v),
        None => String::new(),
    }
}

/// Whether `c` can start a JS identifier.
fn is_ident_start(c: char) -> bool {
    c.is_ascii_alphabetic() || c == '_' || c == '$'
}

/// Whether `c` can continue a JS identifier.
fn is_ident_continue(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_' || c == '$'
}

/// Rewrite a template expression string (e.g. `count > 0`, `user.name`,
/// `items.length`) into valid JS that reads from the component's reactive
/// `scope()` accessor, so `condition`/`bind` strings from the IR can be
/// dropped straight into a JSX expression container.
///
/// - String literals (single/double quoted) are left untouched.
/// - Bare identifiers are prefixed with `scope().`, except those in `locals`
///   (real JS values from an enclosing `For`) and JS literal keywords
///   (`true`, `false`, `null`, `undefined`).
/// - Only the first segment of a dotted path is prefixed: `user.name` becomes
///   `scope().user.name`, never `scope().user.scope().name`.
/// - An empty/whitespace expression becomes `undefined`.
fn scope_expr(expr: &str, locals: &[String]) -> String {
    if expr.trim().is_empty() {
        return "undefined".to_string();
    }
    let chars: Vec<char> = expr.chars().collect();
    let mut out = String::new();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c == '\'' || c == '"' {
            let quote = c;
            out.push(c);
            i += 1;
            while i < chars.len() {
                let cc = chars[i];
                out.push(cc);
                i += 1;
                if cc == '\\' && i < chars.len() {
                    out.push(chars[i]);
                    i += 1;
                    continue;
                }
                if cc == quote {
                    break;
                }
            }
            continue;
        }
        if is_ident_start(c) {
            let prev_is_dot = out.trim_end().ends_with('.');
            let start = i;
            while i < chars.len() && is_ident_continue(chars[i]) {
                i += 1;
            }
            let ident: String = chars[start..i].iter().collect();
            if prev_is_dot
                || locals.iter().any(|l| l == &ident)
                || matches!(ident.as_str(), "true" | "false" | "null" | "undefined")
            {
                out.push_str(&ident);
            } else {
                out.push_str("scope().");
                out.push_str(&ident);
            }
            continue;
        }
        out.push(c);
        i += 1;
    }
    out
}

fn on_click_attr(name: &str) -> String {
    format!(" onClick={{() => handlers().{name}?.()}}")
}

fn dom_event_attr(js_event: &str, name: &str) -> String {
    format!(" {js_event}={{(event) => handlers().{name}?.(event)}}")
}

fn opt_on_click(v: Option<&String>) -> String {
    v.map(|n| on_click_attr(n)).unwrap_or_default()
}

fn opt_dom_event(js_event: &str, v: Option<&String>) -> String {
    v.map(|n| dom_event_attr(js_event, n)).unwrap_or_default()
}

fn opt_on_long_press(v: Option<&String>) -> String {
    v.map(|n| attr("data-crepus-on-long-press", n))
        .unwrap_or_default()
}

fn emit_children(children: &[ViewNode], indent: usize, locals: &[String]) -> String {
    children
        .iter()
        .map(|c| emit_node(c, indent, locals))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Wrap `children` in `tag`, or self-close when there are none.
fn element(
    tag: &str,
    attrs: &str,
    children: &[ViewNode],
    indent: usize,
    locals: &[String],
) -> String {
    let pad = "  ".repeat(indent);
    if children.is_empty() {
        return format!("{pad}<{tag}{attrs} />");
    }
    let inner = emit_children(children, indent + 1, locals);
    format!("{pad}<{tag}{attrs}>\n{inner}\n{pad}</{tag}>")
}

/// `<Show when={COND} fallback={<>...else...</>}> ...then... </Show>`,
/// omitting `fallback` entirely when there is no `else` branch.
fn emit_show(
    condition: &str,
    then_children: &[ViewNode],
    else_children: Option<&Vec<ViewNode>>,
    indent: usize,
    locals: &[String],
) -> String {
    let pad = "  ".repeat(indent);
    let cond = scope_expr(condition, locals);
    let then_inner = emit_children(then_children, indent + 1, locals);
    match else_children {
        None => format!("{pad}<Show when={{{cond}}}>\n{then_inner}\n{pad}</Show>"),
        Some(ec) => {
            let else_inner = emit_children(ec, indent + 2, locals);
            format!(
                "{pad}<Show when={{{cond}}} fallback={{<>\n{else_inner}\n{pad}  </>}}>\n{then_inner}\n{pad}</Show>"
            )
        }
    }
}

/// `<For each={toArray(scope().BIND)}>{(ITEM, index) => (...)}</For>`.
fn emit_for(
    bind: &str,
    item_name: &str,
    item_body: &[ViewNode],
    indent: usize,
    locals: &[String],
) -> String {
    let pad = "  ".repeat(indent);
    let bind_expr = scope_expr(bind, locals);
    let mut inner_locals = locals.to_vec();
    inner_locals.push(item_name.to_string());
    let inner = emit_children(item_body, indent + 1, &inner_locals);
    format!(
        "{pad}<For each={{toArray({bind_expr})}}>{{({item_name}, index) => (\n{inner}\n{pad})}}</For>"
    )
}

fn emit_text_and_media_node(
    node: &ViewNode,
    indent: usize,
    locals: &[String],
    pad: &str,
) -> String {
    match node {
        ViewNode::Text {
            content,
            bind,
            style,
        } => {
            let body = match bind {
                Some(b) => format!("{{{}}}", scope_expr(b, locals)),
                None => jsx_text(content),
            };
            format!("{pad}<span{}>{}</span>", class_attr(style.as_ref()), body)
        }
        ViewNode::Link {
            href,
            target,
            rel,
            style,
            children,
        } => {
            let attrs = format!(
                "{}{}{}{}",
                attr("href", href),
                opt_attr("target", target.as_ref()),
                opt_attr("rel", rel.as_ref()),
                class_attr(style.as_ref())
            );
            element("a", &attrs, children, indent, locals)
        }
        ViewNode::Button {
            label,
            on_click,
            on_long_press,
            style,
        } => format!(
            "{pad}<button type=\"button\"{}{}{}>{}</button>",
            class_attr(style.as_ref()),
            opt_on_click(on_click.as_ref()),
            opt_on_long_press(on_long_press.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Badge {
            label, tone, style, ..
        } => format!(
            "{pad}<span{}{}>{}</span>",
            class_attr(style.as_ref()),
            opt_attr("data-tone", tone.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Image {
            src,
            alt,
            on_long_press,
            style,
            ..
        } => format!(
            "{pad}<img{}{}{}{} />",
            attr("src", src),
            attr("alt", alt.as_deref().unwrap_or("")),
            class_attr(style.as_ref()),
            opt_on_long_press(on_long_press.as_ref())
        ),
        ViewNode::WebView { src, style } => format!(
            "{pad}<iframe{}{} />",
            attr("src", src),
            class_attr(style.as_ref())
        ),
        _ => unreachable!(),
    }
}

fn emit_layout_node(node: &ViewNode, indent: usize, locals: &[String], pad: &str) -> String {
    match node {
        ViewNode::Stack {
            on_long_press,
            style,
            children,
            ..
        } => {
            let attrs = format!(
                "{}{}",
                class_attr(style.as_ref()),
                opt_on_long_press(on_long_press.as_ref())
            );
            element("div", &attrs, children, indent, locals)
        }
        ViewNode::Scroll {
            style, children, ..
        } => element("div", &class_attr(style.as_ref()), children, indent, locals),
        ViewNode::Dropzone {
            on_drop,
            style,
            children,
            ..
        } => {
            let attrs = format!(
                "{}{}",
                class_attr(style.as_ref()),
                opt_dom_event("onDrop", on_drop.as_ref())
            );
            element("div", &attrs, children, indent, locals)
        }
        ViewNode::Divider { style, .. } => {
            format!("{pad}<hr{} />", class_attr(style.as_ref()))
        }
        ViewNode::Spacer { style, .. } => {
            format!(
                "{pad}<div aria-hidden=\"true\"{} />",
                class_attr(style.as_ref())
            )
        }
        ViewNode::SlotRotate {
            phrases,
            interval_ms,
            style,
        } => format!(
            "{pad}<span{} data-interval-ms={{{interval_ms}}}{}>{}</span>",
            attr("data-crepus-slot-rotate", &phrases.join("|")),
            class_attr(style.as_ref()),
            jsx_text(phrases.first().map(String::as_str).unwrap_or(""))
        ),
        _ => unreachable!(),
    }
}

fn emit_input_node(node: &ViewNode, _indent: usize, _locals: &[String], pad: &str) -> String {
    match node {
        ViewNode::Toggle {
            label,
            checked,
            on_change,
            on_long_press,
            style,
            ..
        } => format!(
            "{pad}<button type=\"button\" role=\"switch\" aria-checked={{{}}}{}{}{}>{}</button>",
            checked,
            class_attr(style.as_ref()),
            opt_dom_event("onChange", on_change.as_ref()),
            opt_on_long_press(on_long_press.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Checkbox {
            label,
            checked,
            on_change,
            style,
            ..
        } => format!(
            "{pad}<label{}>\n{pad}  <input type=\"checkbox\" checked={{{}}}{} />\n{pad}  {}\n{pad}</label>",
            class_attr(style.as_ref()),
            checked,
            opt_dom_event("onChange", on_change.as_ref()),
            jsx_text(label)
        ),
        ViewNode::Slider {
            value,
            min,
            max,
            step,
            on_change,
            style,
            ..
        } => format!(
            "{pad}<input type=\"range\" value={{{value}}} min={{{min}}} max={{{max}}}{}{}{} />",
            step.map(|s| format!(" step={{{s}}}")).unwrap_or_default(),
            class_attr(style.as_ref()),
            opt_dom_event("onChange", on_change.as_ref())
        ),
        ViewNode::Progress {
            value, max, style, ..
        } => format!(
            "{pad}<progress value={{{value}}} max={{{max}}}{} />",
            class_attr(style.as_ref())
        ),
        ViewNode::Meter {
            value,
            min,
            max,
            style,
            ..
        } => format!(
            "{pad}<meter value={{{value}}} min={{{min}}} max={{{max}}}{} />",
            class_attr(style.as_ref())
        ),
        ViewNode::Input {
            placeholder,
            bind,
            secure,
            multiline,
            on_change,
            style,
        } => {
            let cls = class_attr(style.as_ref());
            let ph = attr("placeholder", placeholder);
            let name = attr("name", bind);
            let on_change_attr = opt_dom_event("onChange", on_change.as_ref());
            if *multiline {
                format!("{pad}<textarea{ph}{name}{cls}{on_change_attr} />")
            } else {
                let ty = if *secure { "password" } else { "text" };
                format!("{pad}<input type=\"{ty}\"{ph}{name}{cls}{on_change_attr} />")
            }
        },
        ViewNode::Picker {
            options,
            bind,
            on_change,
            style,
        } => {
            let opts: String = options
                .iter()
                .map(|o| {
                    format!(
                        "{pad}  <option{}>{}</option>",
                        attr("value", &o.value),
                        jsx_text(&o.label)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "{pad}<select{}{}{}>\n{opts}\n{pad}</select>",
                attr("name", bind),
                class_attr(style.as_ref()),
                opt_dom_event("onChange", on_change.as_ref())
            )
        },
        ViewNode::FilePicker {
            label,
            accept,
            multiple,
            on_pick,
            style,
        } => {
            let accept_attr = if accept.is_empty() {
                String::new()
            } else {
                attr("accept", &accept.join(","))
            };
            let multiple_attr = if *multiple { " multiple" } else { "" };
            format!(
                "{pad}<label{}>\n{pad}  <input type=\"file\"{accept_attr}{multiple_attr}{} />\n{pad}  {}\n{pad}</label>",
                class_attr(style.as_ref()),
                opt_dom_event("onChange", on_pick.as_ref()),
                jsx_text(label)
            )
        },
        _ => unreachable!(),
    }
}

fn emit_collection_node(node: &ViewNode, indent: usize, locals: &[String], pad: &str) -> String {
    match node {
        ViewNode::List {
            ordered,
            style,
            children,
        } => element(
            if *ordered { "ol" } else { "ul" },
            &class_attr(style.as_ref()),
            children,
            indent,
            locals,
        ),
        ViewNode::ListItem {
            on_long_press,
            style,
            children,
        } => {
            let attrs = format!(
                "{}{}",
                class_attr(style.as_ref()),
                opt_on_long_press(on_long_press.as_ref())
            );
            element("li", &attrs, children, indent, locals)
        }
        ViewNode::Tabs {
            tabs,
            on_change,
            style,
            ..
        } => {
            let cls = class_attr(style.as_ref());
            let buttons: String = tabs
                .iter()
                .map(|t| {
                    let onclick = match on_change {
                        Some(name) => format!(
                            " onClick={{() => handlers().{name}?.({})}}",
                            js_str(&t.value)
                        ),
                        None => String::new(),
                    };
                    format!(
                        "{pad}    <button type=\"button\" role=\"tab\"{onclick}>{}</button>",
                        jsx_text(&t.label)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            let panels: String = tabs
                .iter()
                .map(|t| {
                    format!(
                        "{pad}  <div role=\"tabpanel\">\n{}\n{pad}  </div>",
                        emit_children(&t.children, indent + 2, locals)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "{pad}<div{cls}>\n{pad}  <div role=\"tablist\">\n{buttons}\n{pad}  </div>\n{panels}\n{pad}</div>"
            )
        }
        _ => unreachable!(),
    }
}

fn emit_control_flow_node(node: &ViewNode, indent: usize, locals: &[String], _pad: &str) -> String {
    match node {
        ViewNode::If {
            condition,
            then_children,
            else_children,
            ..
        } => emit_show(
            condition,
            then_children,
            else_children.as_ref(),
            indent,
            locals,
        ),
        ViewNode::ForEach {
            bind,
            item_name,
            item_body,
            ..
        } => emit_for(bind, item_name, item_body, indent, locals),
        _ => unreachable!(),
    }
}

pub(crate) fn emit_node(node: &ViewNode, indent: usize, locals: &[String]) -> String {
    let pad = "  ".repeat(indent);
    match node {
        ViewNode::Text { .. }
        | ViewNode::Link { .. }
        | ViewNode::Button { .. }
        | ViewNode::Badge { .. }
        | ViewNode::Image { .. }
        | ViewNode::WebView { .. } => emit_text_and_media_node(node, indent, locals, &pad),
        ViewNode::Stack { .. }
        | ViewNode::Scroll { .. }
        | ViewNode::Dropzone { .. }
        | ViewNode::Divider { .. }
        | ViewNode::Spacer { .. }
        | ViewNode::SlotRotate { .. } => emit_layout_node(node, indent, locals, &pad),
        ViewNode::Toggle { .. }
        | ViewNode::Checkbox { .. }
        | ViewNode::Slider { .. }
        | ViewNode::Progress { .. }
        | ViewNode::Meter { .. }
        | ViewNode::Input { .. }
        | ViewNode::Picker { .. }
        | ViewNode::FilePicker { .. } => emit_input_node(node, indent, locals, &pad),
        ViewNode::List { .. } | ViewNode::ListItem { .. } | ViewNode::Tabs { .. } => {
            emit_collection_node(node, indent, locals, &pad)
        }
        ViewNode::If { .. } | ViewNode::ForEach { .. } => {
            emit_control_flow_node(node, indent, locals, &pad)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::render_template_to_ir;
    use crepuscularity_core::context::TemplateContext;

    fn sample_ir() -> ViewIr {
        let source = r#"stack col gap-2
 text "hi"
 button "Go"
"#;
        render_template_to_ir(source, &TemplateContext::new()).expect("ir")
    }

    #[test]
    fn solid_emit_writes_real_tsx_with_class() {
        let body = emit_solid_component(&sample_ir(), "Card");
        assert!(body.contains("solid-js"));
        assert!(body.contains("export function Card"));
        assert!(body.contains("export default Card;"));
        assert!(body.contains("data-crepus-root=\"true\""));
        assert!(body.contains("<div class=\"col gap-2\">"));
        assert!(body.contains("<span>hi</span>"));
        assert!(body.contains("<button type=\"button\">Go</button>"));
        assert!(!body.contains("className"));
        assert!(!body.contains("TODO"));
    }

    #[test]
    fn emits_scope_and_handlers_props_contract() {
        let body = emit_solid_component(&sample_ir(), "Card");
        assert!(body
            .contains("export type CardProps = { scope?: Record<string, any>; handlers?: Record<string, any> };"));
        assert!(body.contains("const scope = () => props.scope ?? {};"));
        assert!(body.contains("const handlers = () => props.handlers ?? {};"));
    }

    // ── scope_expr ──────────────────────────────────────────────────────────

    #[test]
    fn scope_expr_leaves_string_literals_untouched() {
        assert_eq!(scope_expr(r#"x == "yes""#, &[]), r#"scope().x == "yes""#);
        assert_eq!(scope_expr("x == 'yes'", &[]), "scope().x == 'yes'");
    }

    #[test]
    fn scope_expr_prefixes_dotted_path_once() {
        assert_eq!(scope_expr("user.name", &[]), "scope().user.name");
        assert_eq!(scope_expr("a.b.c", &[]), "scope().a.b.c");
    }

    #[test]
    fn scope_expr_does_not_prefix_locals() {
        assert_eq!(
            scope_expr("item.active", &["item".to_string()]),
            "item.active"
        );
    }

    #[test]
    fn scope_expr_does_not_prefix_keywords() {
        assert_eq!(scope_expr("true", &[]), "true");
        assert_eq!(scope_expr("x == null", &[]), "scope().x == null");
        assert_eq!(scope_expr("x || undefined", &[]), "scope().x || undefined");
    }

    #[test]
    fn scope_expr_empty_becomes_undefined() {
        assert_eq!(scope_expr("", &[]), "undefined");
        assert_eq!(scope_expr("   ", &[]), "undefined");
    }

    // ── class attribute (not className) ───────────────────────────────────

    #[test]
    fn class_attr_uses_class_not_class_name() {
        let node = ViewNode::Stack {
            axis: crate::ir::StackAxis::Column,
            spacing: None,
            align_items: None,
            justify_content: None,
            on_long_press: None,
            style: Some(ViewStyle {
                classes: vec!["a".to_string(), "b".to_string()],
                ..Default::default()
            }),
            children: vec![],
        };
        let out = emit_node(&node, 0, &[]);
        assert_eq!(out, "<div class=\"a b\" />");
    }

    // ── events ──────────────────────────────────────────────────────────────

    #[test]
    fn button_on_click_wired_to_handlers_accessor() {
        let node = ViewNode::Button {
            label: "Go".to_string(),
            on_click: Some("go".to_string()),
            on_long_press: None,
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("onClick={() => handlers().go?.()}"), "{out}");
    }

    #[test]
    fn dom_event_wired_to_handlers_accessor() {
        let node = ViewNode::Checkbox {
            label: "Agree".to_string(),
            bind: None,
            checked: false,
            on_change: Some("agree".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains("onChange={(event) => handlers().agree?.(event)}"),
            "{out}"
        );
    }

    // ── bind ────────────────────────────────────────────────────────────────

    #[test]
    fn text_with_bind_renders_scope_accessor_expression() {
        let node = ViewNode::Text {
            content: "placeholder".to_string(),
            bind: Some("user.name".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert_eq!(out, "<span>{scope().user.name}</span>");
    }

    // ── Show ────────────────────────────────────────────────────────────────

    #[test]
    fn show_without_fallback_omits_fallback_attr() {
        let node = ViewNode::If {
            condition: "count > 0".to_string(),
            then_children: vec![ViewNode::Text {
                content: "yes".to_string(),
                bind: None,
                style: None,
            }],
            else_children: None,
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.starts_with("<Show when={scope().count > 0}>"), "{out}");
        assert!(!out.contains("fallback"), "{out}");
        assert!(out.contains("<span>yes</span>"), "{out}");
        assert!(out.trim_end().ends_with("</Show>"), "{out}");
    }

    #[test]
    fn show_with_fallback_renders_both_branches() {
        let node = ViewNode::If {
            condition: "count > 0".to_string(),
            then_children: vec![ViewNode::Text {
                content: "yes".to_string(),
                bind: None,
                style: None,
            }],
            else_children: Some(vec![ViewNode::Text {
                content: "no".to_string(),
                bind: None,
                style: None,
            }]),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("fallback={<>"), "{out}");
        assert!(out.contains("<span>yes</span>"), "{out}");
        assert!(out.contains("<span>no</span>"), "{out}");
    }

    // ── For ─────────────────────────────────────────────────────────────────

    #[test]
    fn for_each_maps_over_scope_array_and_item_is_not_prefixed() {
        let node = ViewNode::ForEach {
            bind: "items".to_string(),
            item_name: "item".to_string(),
            item_body: vec![ViewNode::Text {
                content: "".to_string(),
                bind: Some("item.name".to_string()),
                style: None,
            }],
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.starts_with("<For each={toArray(scope().items)}>{(item, index) => ("),
            "{out}"
        );
        assert!(out.contains("{item.name}"), "{out}");
        assert!(!out.contains("scope().item.name"), "{out}");
        assert!(out.trim_end().ends_with(")}</For>"), "{out}");
    }

    #[test]
    fn nested_for_resolves_both_item_names_as_locals() {
        let inner = ViewNode::ForEach {
            bind: "outer.children".to_string(),
            item_name: "inner".to_string(),
            item_body: vec![ViewNode::Text {
                content: "".to_string(),
                bind: Some("inner.label".to_string()),
                style: None,
            }],
            style: None,
        };
        let node = ViewNode::ForEach {
            bind: "items".to_string(),
            item_name: "outer".to_string(),
            item_body: vec![inner],
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains("<For each={toArray(scope().items)}>{(outer, index)"),
            "{out}"
        );
        assert!(
            out.contains("<For each={toArray(outer.children)}>{(inner, index)"),
            "{out}"
        );
        assert!(out.contains("{inner.label}"), "{out}");
        assert!(!out.contains("scope().inner.label"), "{out}");
        assert!(!out.contains("scope().outer.children"), "{out}");
    }

    // ── one test per remaining ViewNode variant ────────────────────────────

    #[test]
    fn emits_text() {
        let node = ViewNode::Text {
            content: "hi".to_string(),
            bind: None,
            style: None,
        };
        assert_eq!(emit_node(&node, 0, &[]), "<span>hi</span>");
    }

    #[test]
    fn emits_stack() {
        let node = ViewNode::Stack {
            axis: crate::ir::StackAxis::Column,
            spacing: None,
            align_items: None,
            justify_content: None,
            on_long_press: Some("press".to_string()),
            style: None,
            children: vec![],
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains(r#"data-crepus-on-long-press="press""#),
            "{out}"
        );
    }

    #[test]
    fn emits_button() {
        let node = ViewNode::Button {
            label: "Go".to_string(),
            on_click: None,
            on_long_press: None,
            style: None,
        };
        assert_eq!(
            emit_node(&node, 0, &[]),
            "<button type=\"button\">Go</button>"
        );
    }

    #[test]
    fn emits_toggle() {
        let node = ViewNode::Toggle {
            label: "On".to_string(),
            bind: None,
            checked: true,
            on_change: Some("toggle".to_string()),
            on_long_press: None,
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains("onChange={(event) => handlers().toggle?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_checkbox() {
        let node = ViewNode::Checkbox {
            label: "Agree".to_string(),
            bind: None,
            checked: false,
            on_change: Some("agree".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains("onChange={(event) => handlers().agree?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_slider() {
        let node = ViewNode::Slider {
            label: None,
            bind: None,
            value: 5.0,
            min: 0.0,
            max: 10.0,
            step: Some(1.0),
            on_change: Some("vol".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("type=\"range\""), "{out}");
        assert!(
            out.contains("onChange={(event) => handlers().vol?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_progress() {
        let node = ViewNode::Progress {
            label: None,
            value: 3.0,
            max: 10.0,
            style: None,
        };
        assert_eq!(emit_node(&node, 0, &[]), "<progress value={3} max={10} />");
    }

    #[test]
    fn emits_meter() {
        let node = ViewNode::Meter {
            label: None,
            value: 3.0,
            min: 0.0,
            max: 10.0,
            style: None,
        };
        assert_eq!(
            emit_node(&node, 0, &[]),
            "<meter value={3} min={0} max={10} />"
        );
    }

    #[test]
    fn emits_badge() {
        let node = ViewNode::Badge {
            label: "New".to_string(),
            tone: Some("info".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("data-tone=\"info\""), "{out}");
    }

    #[test]
    fn emits_divider() {
        let node = ViewNode::Divider {
            axis: crate::ir::StackAxis::Row,
            style: None,
        };
        assert_eq!(emit_node(&node, 0, &[]), "<hr />");
    }

    #[test]
    fn emits_spacer() {
        let node = ViewNode::Spacer {
            size: None,
            style: None,
        };
        assert_eq!(emit_node(&node, 0, &[]), "<div aria-hidden=\"true\" />");
    }

    #[test]
    fn emits_dropzone() {
        let node = ViewNode::Dropzone {
            label: "Drop here".to_string(),
            accept: None,
            on_drop: Some("drop".to_string()),
            style: None,
            children: vec![],
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains("onDrop={(event) => handlers().drop?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_file_picker() {
        let node = ViewNode::FilePicker {
            label: "Upload".to_string(),
            accept: vec!["image/*".to_string()],
            multiple: true,
            on_pick: Some("upload".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("type=\"file\""), "{out}");
        assert!(out.contains("accept=\"image/*\""), "{out}");
        assert!(out.contains("multiple"), "{out}");
        assert!(
            out.contains("onChange={(event) => handlers().upload?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_image() {
        let node = ViewNode::Image {
            src: "cat.png".to_string(),
            alt: Some("A cat".to_string()),
            placeholder: None,
            on_long_press: Some("press".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("src=\"cat.png\""), "{out}");
        assert!(
            out.contains(r#"data-crepus-on-long-press="press""#),
            "{out}"
        );
    }

    #[test]
    fn emits_link() {
        let node = ViewNode::Link {
            href: "/about".to_string(),
            target: None,
            rel: None,
            style: None,
            children: vec![],
        };
        assert_eq!(emit_node(&node, 0, &[]), "<a href=\"/about\" />");
    }

    #[test]
    fn emits_web_view() {
        let node = ViewNode::WebView {
            src: "https://example.com".to_string(),
            style: None,
        };
        assert_eq!(
            emit_node(&node, 0, &[]),
            "<iframe src=\"https://example.com\" />"
        );
    }

    #[test]
    fn emits_scroll() {
        let node = ViewNode::Scroll {
            axis: crate::ir::StackAxis::Column,
            style: None,
            children: vec![],
        };
        assert_eq!(emit_node(&node, 0, &[]), "<div />");
    }

    #[test]
    fn emits_list() {
        let node = ViewNode::List {
            ordered: true,
            style: None,
            children: vec![],
        };
        assert_eq!(emit_node(&node, 0, &[]), "<ol />");
    }

    #[test]
    fn emits_list_item() {
        let node = ViewNode::ListItem {
            on_long_press: Some("press".to_string()),
            style: None,
            children: vec![],
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains(r#"data-crepus-on-long-press="press""#),
            "{out}"
        );
    }

    #[test]
    fn emits_slot_rotate() {
        let node = ViewNode::SlotRotate {
            phrases: vec!["hi".to_string(), "bye".to_string()],
            interval_ms: 500,
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("data-crepus-slot-rotate=\"hi|bye\""), "{out}");
        assert!(out.contains(">hi</span>"), "{out}");
    }

    #[test]
    fn emits_input() {
        let node = ViewNode::Input {
            placeholder: "Name".to_string(),
            bind: "name".to_string(),
            multiline: false,
            secure: false,
            on_change: Some("nameChanged".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(out.contains("placeholder=\"Name\""), "{out}");
        assert!(
            out.contains("onChange={(event) => handlers().nameChanged?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_picker() {
        let node = ViewNode::Picker {
            bind: "color".to_string(),
            options: vec![],
            on_change: Some("colorChanged".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains("onChange={(event) => handlers().colorChanged?.(event)}"),
            "{out}"
        );
    }

    #[test]
    fn emits_tabs() {
        let node = ViewNode::Tabs {
            bind: "tab".to_string(),
            tabs: vec![crate::ir::TabItem {
                value: "one".to_string(),
                label: "One".to_string(),
                icon: None,
                children: vec![],
            }],
            on_change: Some("tabChanged".to_string()),
            style: None,
        };
        let out = emit_node(&node, 0, &[]);
        assert!(
            out.contains("onClick={() => handlers().tabChanged?.(\"one\")}"),
            "{out}"
        );
    }
}
