// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

const c = @cImport({
    @cInclude("crepuscularity_abi.h");
});

pub const crepus_last_error = c.crepus_last_error;
pub const crepus_string_free = c.crepus_string_free;
