// Auto-generated by `crepus plugins bindgen` (equilibrium-ffi)
// Source: /Users/undivisible/projects/crepuscularity/crates/crepuscularity-abi/include/crepuscularity_abi.h

// Generated by equilibrium-ffi for a scriptc host.
// Bound to native symbols by crepuscularity_abi.ffi.json; build with
// `scriptc build <entry>.ts --ffi crepuscularity_abi.ffi.json -o <app>`.
//
// Length-delimited spans arrive as Uint8Array; encode text with
// TextEncoder, or declare the span as `string` through
// ImportOptions::scriptc_string_spans.

// No C ABI safe functions were found in the header.
